title: Naveen Kumar R | Senior SDE & System Architect
description: Portfolio and Resume of Naveen Kumar R, specializing in System Architecture and Senior Software Development.
theme: jekyll-theme-minimal
